spring.datasource.url: ${DB_URL}
spring.datasource.driverClassName: com.mysql.cj.jdbc.Driver
spring.datasource.username: ${DB_USER}
spring.datasource.password: ${DB_ACCESS_KEY}


spring.datasource.hikari.connection-timeout: 30000
spring.datasource.hikari.maximum-pool-size: 10
spring.datasource.hikari.minimum-idle: 5
spring.datasource.hikari.idle-timeout: 30000


spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        temp:
          use_jdbc_metadata_defaults: true

springdoc:
  api-docs:
    enabled: true
