spring:
  datasource:
    url: ${DB_URL}
    driverClassName: com.mysql.cj.jdbc.Driver
    username: ${DB_USER}
    password: ${DB_ACCESS_KEY}
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
      minimum-idle: 10
      idle-timeout: 600000
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        temp:
          use_jdbc_metadata_defaults: true

springdoc:
  api-docs:
    enabled: true
